### ISSUE TITLE
How to return query data back to the object that requested it

### ISSUE THREAD

**Issue by thomasstevens89** [angular-ui/AngularJS-StyleGuide#6]
https://github.com/ProLoser/AngularJS-ORM/blob/master/modules/Objects.coffee#L39-L40

The `query()` function in BaseObject just pushes the payload to the SocketObject queryStream, which is then responsible for performing the actual query. But how does the data get returned to the original object that requested it?

Is there some sort of callback on the event/payload that allows the socket to return a promise?

While I'm still experimenting with all this, I'm not using sockets myself, instead I just have a `dataManager` object in place of the socket which will query a REST service.

I know you have that section in the code marked as TODO, but if you could point me in the right direction I'd really appreciate it. Thanks

**Comment by ProLoser** [comment]
Removed the socket stuff
