### ISSUE TITLE
Common downStream Bus

### ISSUE THREAD

**Issue by thomasstevens89** [angular-ui/AngularJS-StyleGuide#7]
At the moment, new objects create their own upstream bus in the construct function which then gets merged/plugged in to the parent upstream bus. However all objects share the same downstream bus (initiated in the socket object and then passed along down through the collections).

Should we be creating a new downstream bus in the construct function of new objects also? That would allow us to filter only the relevant events and pass them into the child's own downstream bus.

**Comment by ProLoser** [comment]
Removed the socket stuff
